version: '2.0'

volumes:
  datavolume:

services:

  db:
    image: mdillon/postgis
    volumes:
      - datavolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    ports:
      - 8081:8080

  wps-server:
    image: wps-server
    ports:
      - 5000:5000
